"""Shared evaluation core for the RecoverIQ late-payment models.

The three trainers — train_xgboost.py, train_random_forest.py,
train_gradient_boosting.py — each own their model and nothing else. Data
loading, the metric definitions, the fold construction and the stability
check all live here, imported by all three.

That split is deliberate. The six scripts this replaced each carried their
own copy of the split loading and scoring, drifted apart, and ended up
reporting numbers that were not comparable with one another: one trained
on late_payment_strict while the pipeline declared
late_payment_weekend_adjusted canonical, and the committed metrics had
been generated by a still older version. A comparison table is only worth
reading if every row was produced by the same code.

WHY THE HEADLINE METRIC IS WITHIN-PERIOD AUC
--------------------------------------------
The late rate moves hard across the validation window:

    2015-10   63.2%
    2015-11   39.0%
    2015-12   29.7%

Pooled ROC-AUC over a window like that conflates two questions — "is this
invoice riskier than that one" and "is this month riskier than that
month" — and a model with no access to the period cannot answer the
second. The effect is big enough to invert the metric: one run scored
0.5481 pooled while every individual month inside it scored 0.57-0.61. A
pooled figure below every one of its own components is measuring drift,
not skill.

So within_period_auc ranks invoices only against others posted in the
same month, weighted by month size. pooled_roc_auc is still reported,
because omitting it would be its own kind of dishonesty, but it is not
what models are selected on.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    brier_score_loss,
    f1_score,
    log_loss,
    precision_score,
    recall_score,
    roc_auc_score,
)

from app.ml.payment_features import (
    CATEGORICAL_FEATURES as MODEL_CATEGORICAL_FEATURES,
    NUMERIC_FEATURES as MODEL_NUMERIC_FEATURES,
    TARGET_COLUMN,
)

PROJECT_ROOT = Path(__file__).resolve().parents[3]
SPLIT_DIR = PROJECT_ROOT / "data" / "processed" / "primary" / "splits"
ARTIFACT_ROOT = Path(__file__).parent / "artifacts" / "models"

RANDOM_STATE = 42

# Rows with less history than this are excluded from a fold's score. The
# causal history features need accumulated history, so the earliest fold
# has almost none; the previous selection score averaged those near-chance
# folds in and came out anti-correlated with validation, actively
# preferring the models that used history worst.
MIN_HISTORY_FOR_SCORING = 3

FEATURES = MODEL_NUMERIC_FEATURES + MODEL_CATEGORICAL_FEATURES


def load(name: str) -> pd.DataFrame:
    path = SPLIT_DIR / f"{name}.csv.gz"
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found. Run `python -m app.ml.datasets.build_primary_features` "
            "then `python -m app.ml.datasets.create_primary_splits` first."
        )
    return pd.read_csv(path, parse_dates=["doc_date", "posting_date", "net_due_date"])


def load_splits() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """train, validation, test. Test is returned so category levels can be
    aligned across all three; no trainer may read its target."""
    return load("train"), load("validation"), load("test")


def category_levels_from_train(
    train_frame: pd.DataFrame,
) -> dict[str, list[str]]:
    return {
        column: sorted(
            train_frame[column]
            .dropna()
            .astype(str)
            .unique()
            .tolist()
        )
        for column
        in MODEL_CATEGORICAL_FEATURES
    }


def prepare_categorical(
    frames: list[pd.DataFrame],
) -> list[pd.DataFrame]:
    """Prepare native categorical features using train-only vocabulary.

    The first frame must be the training frame. Category levels are learned
    only from it. Unseen categories in later frames become missing values
    rather than leaking future category vocabulary into training.
    """
    if not frames:
        return []

    train_frame = frames[0]

    category_levels = (
        category_levels_from_train(
            train_frame
        )
    )

    prepared: list[pd.DataFrame] = []

    for frame in frames:
        X = frame[FEATURES].copy()

        for column in MODEL_CATEGORICAL_FEATURES:
            values = frame[column].astype("string")

            X[column] = pd.Categorical(
                values,
                categories=category_levels[column],
            )

        prepared.append(X)

    return prepared


def to_numeric_codes(frames: list[pd.DataFrame], medians: pd.Series | None = None):
    """Integer-code the categoricals and median-fill NaNs.

    For scikit-learn estimators, which have neither native categorical
    support nor native NaN handling. The medians come from TRAIN only and
    are returned so they can be saved alongside the model: the saved
    estimator is unusable without them, because scoring a raw frame against
    it silently produces wrong answers rather than an error.
    """
    coded = []
    for frame in frames:
        X = frame.copy()
        for column in MODEL_CATEGORICAL_FEATURES:
            X[column] = X[column].cat.codes
        coded.append(X)
    if medians is None:
        medians = coded[0].median()
    return [X.fillna(medians) for X in coded], medians


def within_period_auc(frame: pd.DataFrame, probabilities: np.ndarray) -> tuple[float, dict]:
    months = frame["posting_date"].dt.to_period("M")
    scores, weights, per_month = [], [], {}
    for month in months.unique():
        mask = (months == month).to_numpy()
        y = frame.loc[mask, TARGET_COLUMN]
        if y.nunique() < 2:
            continue
        auc = float(roc_auc_score(y, probabilities[mask]))
        per_month[str(month)] = {
            "rows": int(mask.sum()),
            "late_rate": round(float(y.mean()), 4),
            "auc": round(auc, 4),
        }
        scores.append(auc)
        weights.append(int(mask.sum()))
    if not scores:
        return float("nan"), {}
    return float(np.average(scores, weights=weights)), per_month


def evaluate(frame: pd.DataFrame, probabilities: np.ndarray, threshold: float = 0.5) -> dict:
    y = frame[TARGET_COLUMN]
    predicted = (probabilities >= threshold).astype(int)
    weighted, per_month = within_period_auc(frame, probabilities)
    return {
        "within_period_auc": round(weighted, 4),
        "pooled_roc_auc": round(float(roc_auc_score(y, probabilities)), 4),
        "pooled_pr_auc": round(float(average_precision_score(y, probabilities)), 4),
        "log_loss": round(float(log_loss(y, probabilities)), 4),
        "brier": round(float(brier_score_loss(y, probabilities)), 4),
        "accuracy": round(float(accuracy_score(y, predicted)), 4),
        "precision": round(float(precision_score(y, predicted, zero_division=0)), 4),
        "recall": round(float(recall_score(y, predicted, zero_division=0)), 4),
        "f1": round(float(f1_score(y, predicted, zero_division=0)), 4),
        "per_month": per_month,
    }


def temporal_folds(frame: pd.DataFrame, n_folds: int = 4) -> list[tuple[np.ndarray, np.ndarray]]:
    """Expanding-window folds on whole posting dates."""
    daily = frame.groupby("posting_date", sort=True).size().cumsum()
    fractions = np.linspace(0.40, 1.00, n_folds + 1)
    cutoffs = [
        daily.index[int(np.argmin(np.abs(daily.to_numpy() - fraction * len(frame))))]
        for fraction in fractions
    ]
    folds = []
    for index in range(n_folds):
        train_mask = frame["posting_date"] <= cutoffs[index]
        test_mask = (frame["posting_date"] > cutoffs[index]) & (
            frame["posting_date"] <= cutoffs[index + 1]
        )
        if test_mask.sum() == 0 or frame.loc[train_mask, TARGET_COLUMN].nunique() < 2:
            continue
        folds.append(
            (np.flatnonzero(train_mask.to_numpy()), np.flatnonzero(test_mask.to_numpy()))
        )
    return folds


def stability_report(fold_aucs: list[float], fold_base_rates: list[dict]) -> dict:
    """Does this model hold up across time, or is one good window luck?

    A fold below 0.50 means the ranking is REVERSED in that period, which
    is worse than having no model. Every candidate configuration tested so
    far inverts on the same fold, so this is a property of the data rather
    than of any one model's hyperparameters — which is precisely why it
    belongs in every model's report and not in a footnote.
    """
    if not fold_aucs:
        return {"stable": False, "reason": "no scoreable folds"}
    inverted = [round(a, 4) for a in fold_aucs if a < 0.50]
    return {
        "fold_aucs": [round(a, 4) for a in fold_aucs],
        "mean": round(float(np.mean(fold_aucs)), 4),
        "min": round(float(np.min(fold_aucs)), 4),
        "max": round(float(np.max(fold_aucs)), 4),
        "std": round(float(np.std(fold_aucs)), 4),
        "inverted_folds": inverted,
        "fold_base_rates": fold_base_rates,
        "stable": not inverted and float(np.std(fold_aucs)) < 0.10,
    }


def print_stability(stability: dict) -> None:
    print()
    print("  STABILITY VERDICT")
    if stability.get("stable"):
        print("    stable: fold scores agree and none invert.")
        return
    print("    NOT STABLE. This is the headline finding, not a footnote.")
    inverted = stability.get("inverted_folds") or []
    if inverted:
        print(f"    {len(inverted)} fold(s) scored BELOW 0.50 ({inverted}) — the ranking")
        print("    is reversed in those periods, which is worse than no model at all.")
    print(f"    fold std {stability['std']:.4f} across {stability['min']:.4f}-{stability['max']:.4f}.")
    print()
    print("    Cause: the late rate shifts between adjacent five-week windows, so a")
    print("    model calibrated on one regime ranks backwards in the next:")
    for number, rates in enumerate(stability.get("fold_base_rates", [])):
        print(f"      fold {number}: train late {rates['train_late_rate']:.4f}"
              f"  ->  test late {rates['test_late_rate']:.4f}")
    print()
    print("    That is a process-level regime change in when payment runs fire, not")
    print("    invoice-level credit risk. The validation figure is one window that")
    print("    resembled its training period and must NOT be quoted as expected")
    print("    performance.")


def fold_base_rates(frame: pd.DataFrame, folds) -> list[dict]:
    return [
        {
            "train_late_rate": round(float(frame[TARGET_COLUMN].iloc[tr].mean()), 4),
            "test_late_rate": round(float(frame[TARGET_COLUMN].iloc[te].mean()), 4),
        }
        for tr, te in folds
    ]


def baselines(train: pd.DataFrame, validation: pd.DataFrame) -> dict:
    """What any model has to beat to be worth having.

    A constant at the base rate, and the customer's own historical late
    rate. The second is the one that matters: if a model cannot beat a
    per-customer lookup table, it is a lookup table with extra steps.
    """
    base_rate = float(train[TARGET_COLUMN].mean())
    history = train.groupby("cust_num")[TARGET_COLUMN].mean()
    return {
        "constant_base_rate": evaluate(
            validation, np.full(len(validation), base_rate)
        ),
        "customer_history": evaluate(
            validation,
            validation["cust_num"].map(history).fillna(base_rate).to_numpy(),
        ),
    }


def print_data_summary(train, validation, test, model_name: str) -> None:
    print("=" * 78)
    print(f"{model_name.upper()}  —  RecoverIQ late-payment model")
    print("=" * 78)
    print(f"  train      {len(train):>6} rows  {train.posting_date.min().date()} -> "
          f"{train.posting_date.max().date()}  late {train[TARGET_COLUMN].mean():.4f}")
    print(f"  validation {len(validation):>6} rows  {validation.posting_date.min().date()} -> "
          f"{validation.posting_date.max().date()}  late {validation[TARGET_COLUMN].mean():.4f}")
    print(f"  test       {len(test):>6} rows  RESERVED, not read")
    print(f"  features   {len(MODEL_NUMERIC_FEATURES)} numeric + "
          f"{len(MODEL_CATEGORICAL_FEATURES)} categorical")
    print(f"  target     {TARGET_COLUMN}")


def write_report(model_slug: str, report: dict) -> Path:
    directory = ARTIFACT_ROOT / model_slug
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / "report.json"
    path.write_text(json.dumps(report, indent=2) + "\n")
    return path


def print_comparison_row_header() -> None:
    print(f"  {'model':<28} {'within':>8} {'pooled':>8} {'logloss':>9} {'brier':>8}")
    print("  " + "-" * 64)


def print_comparison_row(name: str, scored: dict) -> None:
    print(f"  {name:<28} {scored['within_period_auc']:>8.4f} "
          f"{scored['pooled_roc_auc']:>8.4f} {scored['log_loss']:>9.4f} "
          f"{scored['brier']:>8.4f}")
