"""connect payment risk runtime

Revision ID: 5775ef69e805
Revises: 2de3952113e0
Create Date: 2026-10-03 10:14:11.971690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5775ef69e805'
down_revision: Union[str, Sequence[str], None] = '2de3952113e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('late_payment_probability', sa.Numeric(precision=7, scale=6), nullable=True))
    op.add_column('invoices', sa.Column('payment_risk_model', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('payment_risk_scored_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('payment_risk_drivers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('invoices', sa.Column('payment_risk_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'payment_risk_features')
    op.drop_column('invoices', 'payment_risk_drivers')
    op.drop_column('invoices', 'payment_risk_scored_at')
    op.drop_column('invoices', 'payment_risk_model')
    op.drop_column('invoices', 'late_payment_probability')
    # ### end Alembic commands ###
