"""add payment risk inference fields

Revision ID: 9773b520c91c
Revises: e1a7c3b94d20
Create Date: 2026-10-03 05:21:58.155428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9773b520c91c'
down_revision: Union[str, Sequence[str], None] = 'e1a7c3b94d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('zipcode', sa.String(length=30), nullable=True))
    op.add_column('invoices', sa.Column('posting_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('payment_method_description', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'payment_method_description')
    op.drop_column('invoices', 'posting_date')
    op.drop_column('companies', 'zipcode')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'region')
    # ### end Alembic commands ###
