"""initial schema

Revision ID: d43c032f30e9
Revises: 
Create Date: 2026-09-04 00:33:17.013205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd43c032f30e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('segment', sa.Enum('SMB', 'MID_MARKET', 'ENTERPRISE', name='company_segment'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_table('invoices',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PAID', 'PARTIALLY_PAID', 'OVERDUE', 'WRITTEN_OFF', 'CANCELLED', name='invoice_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_invoices_company_id'), 'invoices', ['company_id'], unique=False)
    op.create_index('ix_invoices_due_date_status', 'invoices', ['due_date', 'status'], unique=False)
    op.create_table('payment_events',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('INVOICE_CREATED', 'INVOICE_OVERDUE', 'PAYMENT_RECEIVED', 'PAYMENT_FAILED', 'PAYMENT_PARTIAL', name='payment_event_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_events_invoice_id'), 'payment_events', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.Enum('BANK_TRANSFER', 'CARD', 'UPI', 'CHEQUE', 'OTHER', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', name='payment_status'), nullable=False),
    sa.Column('reference_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_table('recovery_cases',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'MONITORING', 'ESCALATED', 'RECOVERED', 'CLOSED_UNRECOVERED', 'CLOSED', name='recovery_case_status'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revenue_at_risk', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recovered_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risk_level'), nullable=True),
    sa.Column('recovery_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recovery_window_deadline', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id')
    )
    op.create_index(op.f('ix_recovery_cases_company_id'), 'recovery_cases', ['company_id'], unique=False)
    op.create_index('ix_recovery_cases_status', 'recovery_cases', ['status'], unique=False)
    op.create_table('agent_decisions',
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('DIAGNOSIS', 'INTERVENTION_RECOMMENDATION', name='agent_decision_stage'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('input_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_decisions_recovery_case_id'), 'agent_decisions', ['recovery_case_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('recovery_case_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.Enum('SYSTEM', 'AI_AGENT', 'POLICY_ENGINE', 'HUMAN', name='audit_actor'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_case_occurred', 'audit_logs', ['recovery_case_id', 'occurred_at'], unique=False)
    op.create_table('communication_logs',
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', name='communication_channel'), nullable=False),
    sa.Column('direction', sa.Enum('OUTBOUND', 'INBOUND', name='communication_direction'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'FAILED', 'SIMULATED', name='communication_status'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_logs_recovery_case_id'), 'communication_logs', ['recovery_case_id'], unique=False)
    op.create_table('promise_to_pay',
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('promised_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('promised_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FULFILLED', 'BROKEN', 'EXPIRED', name='promise_to_pay_status'), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promise_to_pay_invoice_id'), 'promise_to_pay', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_promise_to_pay_recovery_case_id'), 'promise_to_pay', ['recovery_case_id'], unique=False)
    op.create_index('ix_promise_to_pay_status_date', 'promise_to_pay', ['status', 'promised_date'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('SEND_EMAIL', 'SEND_PAYMENT_LINK', 'TRACK_PROMISE_TO_PAY', 'ESCALATE', 'WAIT', 'CLOSE_CASE', name='recovery_action_type'), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'POLICY_APPROVED', 'POLICY_REJECTED', 'EXECUTED', 'FAILED', name='recovery_action_status'), nullable=False),
    sa.Column('proposed_by', sa.Enum('AI', 'SYSTEM', 'HUMAN', name='proposed_by'), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_actions_recovery_case_id'), 'recovery_actions', ['recovery_case_id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('recovery_action_id', sa.UUID(), nullable=False),
    sa.Column('policy_name', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'REQUIRES_HUMAN_REVIEW', name='policy_decision_result'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_action_id'], ['recovery_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_recovery_action_id'), 'policy_decisions', ['recovery_action_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_decisions_recovery_action_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_recovery_actions_recovery_case_id'), table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index('ix_promise_to_pay_status_date', table_name='promise_to_pay')
    op.drop_index(op.f('ix_promise_to_pay_recovery_case_id'), table_name='promise_to_pay')
    op.drop_index(op.f('ix_promise_to_pay_invoice_id'), table_name='promise_to_pay')
    op.drop_table('promise_to_pay')
    op.drop_index(op.f('ix_communication_logs_recovery_case_id'), table_name='communication_logs')
    op.drop_table('communication_logs')
    op.drop_index('ix_audit_logs_case_occurred', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_decisions_recovery_case_id'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    op.drop_index('ix_recovery_cases_status', table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_company_id'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_payment_events_invoice_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index('ix_invoices_due_date_status', table_name='invoices')
    op.drop_index(op.f('ix_invoices_company_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('companies')
    # ### end Alembic commands ###

    # Alembic's autogenerated downgrade drops the tables but NOT the enum
    # types that op.create_table created inline, so they survived as
    # orphans in the schema. That made the migration one-way in practice:
    # `alembic downgrade base` followed by `alembic upgrade head` failed
    # with `type "company_segment" already exists`, which is exactly what
    # a reviewer checking migration hygiene will try, and what CI now runs.
    for enum_name in (
        'agent_decision_stage',
        'audit_actor',
        'communication_channel',
        'communication_direction',
        'communication_status',
        'company_segment',
        'invoice_status',
        'payment_event_type',
        'payment_method',
        'payment_status',
        'policy_decision_result',
        'promise_to_pay_status',
        'proposed_by',
        'recovery_action_status',
        'recovery_action_type',
        'recovery_case_status',
        'risk_level',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
